### ISSUE TITLE
Using With Plesk (Phusion Passenger(R))

### ISSUE THREAD

**Issue by adamrpostjr** [matthiaaas/express-file-routing#25]
When using with plesk it tries to walk the dir for passenger not the dir of the application itself, this seems to be becuase passenger uses a loader to start the application.

Below are logs:

```
App 80759 output: 80759/T1 age/Spa/SpawnEnvSetupperMain.cpp:747: shellName = 'false' detected as supporting '-l': false
App 80759 output: localhost
App 80759 output: Fri, 19 May 2023 02:08:49 GMT body-parser deprecated undefined extended: provide extended option at index.js:8:17
App 80759 output: node:internal/fs/utils:347
App 80759 output: throw err;
App 80759 output: ^
App 80759 output:
App 80759 output: Error: ENOENT: no such file or directory, scandir '/usr/share/passenger/helper-scripts/routes'
App 80759 output: at Object.readdirSync (node:fs:1452:3)
App 80759 output: at walkTree (/var/www/vhosts/<client>/<domain>/node_modules/express-file-routing/dist/index.js:120:31)
App 80759 output: at createRouter (/var/www/vhosts/<client>/<domain>/node_modules/express-file-routing/dist/index.js:177:19)
App 80759 output: at Object.<anonymous> (/var/www/vhosts/<client>/<domain>/index.js:12:1)
App 80759 output: at Module._compile (node:internal/modules/cjs/loader:1254:14)
App 80759 output: at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
App 80759 output: at Module.load (node:internal/modules/cjs/loader:1117:32)
App 80759 output: at Module._load (node:internal/modules/cjs/loader:958:12)
App 80759 output: at Module.require (node:internal/modules/cjs/loader:1141:19)
App 80759 output: at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:80:25) {
App 80759 output: errno: -2,
App 80759 output: syscall: 'scandir',
App 80759 output: code: 'ENOENT',
App 80759 output: path: '/usr/share/passenger/helper-scripts/routes'
App 80759 output: }
App 80759 output:
App 80759 output: Node.js v18.16.0
```

**Comment by matthiaaas** [comment]
hey @adamrpostjr, thank you for the report.

Right, the router is not walking through the right /routes directory. You can fix this by providing your own `directory` setting when registering your router through the options object:

```ts
app.use("/", router({
  directory: PLESK_DIRECTORY_HERE
}))
```

This is the directory that will be called from `walkTree` using `fs.readdirSync` recursively.

Maybe you can try for yourself what project directory choice works for Plesk. Here is the code that determines the default directory choice:

```ts
const REQUIRE_MAIN_FILE = path.dirname(require.main?.filename || process.cwd())

const files = walkTree(path.join(REQUIRE_MAIN_FILE, "routes"))
```

Please let me know if you need further assistance or come up with a solution.

**Comment by matthiaaas** [comment]
If you're still into this @adamrpostjr, the next major version that is staged to be released soon is currently available for testing via `npm install express-file-routing@beta` and might fix your issue too.

**Comment by matthiaaas** [comment]
Closing due to inactivity.
