### ISSUE TITLE
ReferenceError is crashing express server

### ISSUE THREAD

**Issue by stalingino** [matthiaaas/express-file-routing#33]
`getHandlers` function could wrap the handler with a try/catch function bypassing all parameters. That way, we can avoid any API failures.

**Comment by matthiaaas** [comment]
Could you share an example? @stalingino

**Comment by stalingino** [comment]
given below `/routes/index.ts`
```
import { Request, Response } from "express";

export async function get(req: Request, resp: Response) {
    resp.json({
        hello: WORLD
    })
}
```
where `WOULD` is undefined, would get below error and stops the server:

```
.../routes/index.ts:5
        hello: WORLD
               ^

ReferenceError: WORLD is not defined
    at get (.../routes/index.ts:5:16)
    at Layer.handle (.../node_modules/express/lib/router/layer.js:95:5)
    at next (.../node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (.../node_modules/express/lib/router/route.js:114:3)
    at Layer.handle (.../node_modules/express/lib/router/layer.js:95:5)
    at <anonymous> (.../node_modules/express/lib/router/index.js:284:15)
    at Function.process_params (.../node_modules/express/lib/router/index.js:346:12)
    at next (.../node_modules/express/lib/router/index.js:280:10)
    at jsonParser (.../node_modules/body-parser/lib/types/json.js:110:7)
    at Layer.handle (.../node_modules/express/lib/router/layer.js:95:5)
```

Same can be solved by below `index.ts` having a try/catch
```
import { Request, Response } from "express";

export async function get(req: Request, resp: Response) {
    try {
        resp.json({
            hello: WORLD
        })
    } catch (error) {
        resp.status(500).json({'error': '' + error})
    }
}
```

But, we can avoid this situation by having the same try/catch as part of the handler addition.

change `/src/utils.ts#L121`
```
export const getHandlers = (handler: Handler | Handler[]): Handler[] => {
  if (!Array.isArray(handler)) return [handler]
  return handler
}
```
to something like below or simpler :)
```

export const getHandlers = (handler: Handler | Handler[]): Handler[] => {
  if (!Array.isArray(handler)) {
    const params = Reflect.getMetadata('design:paramtypes', handler) || [];
    if (params.length == 2) {
      return [async (req, resp) {
        try {
          return await handler(req, resp)
        } catch (error) {
          resp.status(500).json({'error': '' + error})
        }
      }]
    } else {
      return [async (req, resp, next) {
        try {
          return await handler(req, resp, next)
        } catch (error) {
          resp.status(500).json({'error': '' + error})
        }
      }]
    }
  }
  var h = handler[handler.length - 1]
  // handle arrays
}
```

**Comment by matthiaaas** [comment]
hey @stalingino, thank you for providing an example. I am conflicted about this suggestion. I really like the intuitive solution of wrapping the handler's function body with a try/catch.

A ReferenceError is quite a severe code mistake that feels fine to be crashing the Express server. Moreover, error handling is crucial to be in the developer's hands and this library is supposed to leave that to the user.
See also the README's section on error handling.

So I tend to believe that this is the expected and desired behavior and therefore that your provided "solution" is the recommended way to tackle this.

Let me know what your take is on that.

**Comment by stalingino** [comment]
Hi, 

For reference error, what you say is true. But for a missing file unlink, even though i had try catch wrapped, this error stopped the server. Please try below code.

```
try {
  fs.unlinkSync(TEMP + tempFileName + _CSV) // missing file
} catch (error) {
  res.status(500).json({error: "failed"})
}
```

```
Error: ENOENT: no such file or directory, unlink 'temp/ca9b3f7e-d63c-45f8-b371-8abc4f530746.csv'
    at Object.unlinkSync (node:fs:1883:3)
...
 at endReadableNT (node:internal/streams/readable:1359:12) {
  errno: -2,
  syscall: 'unlink',
  code: 'ENOENT',
  path: 'temp/ca9b3f7e-d63c-45f8-b371-8abc4f530746.csv'
}

Node.js v18.17.1
```

**Comment by stalingino** [comment]
I have encountered this error from inside res.download() callback. That means the error got propagated directly to expresssjs which didn't handle the error using the configured error middleware.

**Comment by stalingino** [comment]
invalid issue
